Repository playdata-july-web/july-spring-fullstack, pull requests merged in 2022-07, with the labels that each got.

#21 Refactor dependency injection style
  src/main/java/kr/pe/july/auth/AuthenticationProviderImp.java
  src/main/java/kr/pe/july/auth/UserDetailsServiceImp.java
  src/main/java/kr/pe/july/config/SecurityConfig.java
Labels: refactoring

#25 Update Like feature
  src/main/java/kr/pe/july/auth/AuthenticationProviderImp.java
  src/main/java/kr/pe/july/config/SecurityConfig.java
  src/main/java/kr/pe/july/controller/LikeController.java
  src/main/java/kr/pe/july/controller/SearchController.java
  src/main/java/kr/pe/july/model/dto/LikeDTO.java
  src/main/java/kr/pe/july/model/entity/Like.java
  src/main/java/kr/pe/july/model/entity/User.java
  src/main/java/kr/pe/july/model/repository/LikeRepository.java
  src/main/java/kr/pe/july/model/service/LikeService.java
  src/main/java/kr/pe/july/model/service/SpotService.java
Labels: development

#29 Update connection login and signup
  src/main/java/kr/pe/july/config/SecurityConfig.java
  src/main/java/kr/pe/july/controller/AuthController.java
  src/main/resources/templates/login.html
  src/main/resources/templates/login_form.html
Labels: development

#30 add main_1.html
  src/main/resources/templates/main_1.html
Labels: development

#31 Update connection home
  src/main/java/kr/pe/july/controller/SearchController.java
  src/main/java/kr/pe/july/controller/TemplateController.java
  src/main/resources/templates/index.html
  src/main/webapp/main.html
  src/main/webapp/signup.html
Labels: development

#39 update css
  src/main/resources/static/1.css
  src/main/resources/static/3.css
  src/main/resources/static/login.css
  src/main/resources/static/signup.css
  src/main/resources/static/snsbtn.css
  src/main/resources/templates/css/signup.css
  src/main/resources/templates/index.html
  src/main/resources/templates/login_form.html
  src/main/resources/templates/signup_form.html
Labels: development

#41 Update exception handler
  src/main/java/kr/pe/july/controller/SearchController.java
  src/main/java/kr/pe/july/controller/UserController.java
  src/main/java/kr/pe/july/exception/DuplicateUserException.java
  src/main/java/kr/pe/july/exception/GlobalExceptionHandler.java
  src/main/java/kr/pe/july/exception/SearchResultNotFoundException.java
  src/main/java/kr/pe/july/model/service/UserService.java
Labels: bug, development

#42 Update search view
  src/main/resources/templates/index.html
Labels: development

#44 Release July project 1.0
  .classpath
  .gitignore
  pom.xml
  src/main/java/kr/pe/july/auth/AuthenticationProviderImp.java
  src/main/java/kr/pe/july/auth/UserDetailsServiceImp.java
  src/main/java/kr/pe/july/config/SecurityConfig.java
  src/main/java/kr/pe/july/controller/AuthController.java
  src/main/java/kr/pe/july/controller/LikeController.java
  src/main/java/kr/pe/july/controller/SearchController.java
  src/main/java/kr/pe/july/controller/TemplateController.java
  src/main/java/kr/pe/july/controller/UserController.java
  src/main/java/kr/pe/july/exception/DuplicateUserException.java
  src/main/java/kr/pe/july/exception/GlobalExceptionHandler.java
  src/main/java/kr/pe/july/exception/SearchResultNotFoundException.java
  src/main/java/kr/pe/july/model/dto/LikeDTO.java
  src/main/java/kr/pe/july/model/dto/SpotDTO.java
  src/main/java/kr/pe/july/model/dto/UserCreateForm.java
  src/main/java/kr/pe/july/model/entity/Like.java
  src/main/java/kr/pe/july/model/entity/Spot.java
  src/main/java/kr/pe/july/model/entity/User.java
  src/main/java/kr/pe/july/model/repository/LikeRepository.java
  src/main/java/kr/pe/july/model/repository/SpotRepository.java
  src/main/java/kr/pe/july/model/repository/UserRepository.java
  src/main/java/kr/pe/july/model/service/LikeService.java
  src/main/java/kr/pe/july/model/service/SpotService.java
  src/main/java/kr/pe/july/model/service/UserService.java
  src/main/resources/static/1.css
  src/main/resources/static/3.css
  src/main/resources/static/login.css
  src/main/resources/static/signup.css
  src/main/resources/static/snsbtn.css
  src/main/resources/templates/index.html
  src/main/resources/templates/login_form.html
  src/main/resources/templates/signup_form.html
  target/classes/templates/signup_form.html
  target/m2e-wtp/web-resources/META-INF/maven/playdata/july-spring-fullstack/.gitignore
  target/m2e-wtp/web-resources/META-INF/maven/playdata/july-spring-fullstack/pom.properties
  target/m2e-wtp/web-resources/META-INF/maven/playdata/july-spring-fullstack/pom.xml
Labels: development

#49 Feature/45 lsm
  pom.xml
  src/main/java/kr/pe/july/config/SwaggerConfig.java
  src/main/java/kr/pe/july/controller/AuthController.java
  src/main/java/kr/pe/july/controller/LikeController.java
  src/main/java/kr/pe/july/controller/SearchController.java
  src/main/java/kr/pe/july/controller/TemplateController.java
  src/main/java/kr/pe/july/controller/UserController.java
  src/main/java/kr/pe/july/model/dto/LikeDTO.java
  src/main/java/kr/pe/july/model/dto/SpotDTO.java
  src/main/java/kr/pe/july/model/dto/UserCreateForm.java
  src/main/resources/application.properties
Labels: development

#50 Develop
  pom.xml
  src/main/java/kr/pe/july/config/SwaggerConfig.java
  src/main/java/kr/pe/july/controller/AuthController.java
  src/main/java/kr/pe/july/controller/LikeController.java
  src/main/java/kr/pe/july/controller/SearchController.java
  src/main/java/kr/pe/july/controller/TemplateController.java
  src/main/java/kr/pe/july/controller/UserController.java
  src/main/java/kr/pe/july/model/dto/LikeDTO.java
  src/main/java/kr/pe/july/model/dto/SpotDTO.java
  src/main/java/kr/pe/july/model/dto/UserCreateForm.java
  src/main/resources/application.properties
Labels: documentation
